// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieProject.Data;

namespace MovieProject.Migrations
{
    [DbContext(typeof(MovieProjectContext))]
    partial class MovieProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MovieProject.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Movie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Capen Philips",
                            Rate = 6
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cast Away",
                            Rate = 5
                        },
                        new
                        {
                            Id = 3,
                            Name = " Dolemite is My Name",
                            Rate = 5
                        },
                        new
                        {
                            Id = 4,
                            Name = "It Chapter Two",
                            Rate = 8
                        },
                        new
                        {
                            Id = 5,
                            Name = "Invisible Life",
                            Rate = 7
                        },
                        new
                        {
                            Id = 6,
                            Name = " I Lost My Body",
                            Rate = 8
                        },
                        new
                        {
                            Id = 7,
                            Name = " American Factory",
                            Rate = 6
                        },
                        new
                        {
                            Id = 8,
                            Name = " Plus One",
                            Rate = 3
                        },
                        new
                        {
                            Id = 9,
                            Name = "Crawl",
                            Rate = 7
                        },
                        new
                        {
                            Id = 10,
                            Name = "Space fighter",
                            Rate = 9
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
